# -------- BASE IMAGE -------- #
FROM python:3.10-slim

# -------- WORK DIRECTORY -------- #
WORKDIR /app

# -------- CREATE NON-ROOT USER -------- #
RUN useradd -m sandboxuser

# -------- SWITCH TO SAFE USER -------- #
USER sandboxuser

# -------- ENV SETTINGS -------- #
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# -------- DEFAULT COMMAND -------- #
CMD ["python", "script.py"]