# Env vars that the mock header substitutes inside the sandbox. Kept in a
# single list so the validator/report can surface exactly which substitutions
# happened, rather than labeling all failures as "tests written for pre-patch".
MOCKED_ENV_VARS = [
    "SECRET_API_KEY",
    "DATABASE_URL",
    "API_KEY",
    "API_TOKEN",
    "REDIS_URL",
]


def build_mock_header(source_filename: str = "script.py") -> str:
    return (
        "import builtins, sys, shlex, time, types, os\n"
        "class _MockEnv(dict):\n"
        "    def get(self, key, default=None):\n"
        "        val = super().get(key)\n"
        "        return val if val is not None else (default if default is not None else 'mock-value')\n"
        "    def __missing__(self, key):\n"
        "        return 'mock-value'\n"
        "_env = _MockEnv({k: v for k, v in os.environ.items() if isinstance(k, str)})\n"
        "_env.setdefault('SECRET_API_KEY', 'sk-mock-xxxxxxxxxxxxxxxx')\n"
        "_env.setdefault('DATABASE_URL', 'sqlite:///:memory:')\n"
        "_env.setdefault('API_KEY', 'mock-api-key-12345')\n"
        "_env.setdefault('API_TOKEN', 'mock-api-token-xxxxx')\n"
        "_env.setdefault('REDIS_URL', 'redis://localhost:6379/0')\n"
        "_env.setdefault('PATH', '/usr/local/bin:/usr/bin:/bin:/sbin:/usr/sbin')\n"
        "os.environ = _env\n"
        "class MockInput:\n"
        "    def __init__(self): self.count = 0\n"
        "    def __call__(self, _=''):\n"
        "        self.count += 1\n"
        "        n = self.count\n"
        "        if n == 1: return 'echo hello'\n"
        "        if n == 2: return '[1, 2, 3]'\n"
        "        if n == 3: return 'test'\n"
        "        if n == 4: return '{\"key\": \"value\"}'\n"
        "        return '123'\n"
        "builtins.input = MockInput()\n"
        "def mock_sleep(seconds): pass\n"
        "time.sleep = mock_sleep\n"
        f"sys.argv = ['{source_filename}']\n"
        "_req = types.ModuleType('requests')\n"
        "_mock_json_call = [0]\n"
        "class _MockResp:\n"
        "    status_code = 200\n"
        "    text = '{\"results\":[{\"id\":1,\"name\":\"item1\"}]}'\n"
        "    def json(self):\n"
        "        _mock_json_call[0] += 1\n"
        "        n = _mock_json_call[0]\n"
        "        if n == 1: return {'results': [{'id': 1, 'name': 'item1'}]}\n"
        "        if n == 2: return []\n"
        "        if n == 3: return {'data': {'id': 1, 'value': 'mock'}}\n"
        "        return {}\n"
        "    def raise_for_status(self): pass\n"
        "_req.get = lambda *a, **k: _MockResp()\n"
        "_req.post = lambda *a, **k: _MockResp()\n"
        "_req.put = lambda *a, **k: _MockResp()\n"
        "_req.delete = lambda *a, **k: _MockResp()\n"
        "class _MockSession:\n"
        "    headers = {}\n"
        "    def get(self, *a, **k): return _MockResp()\n"
        "    def post(self, *a, **k): return _MockResp()\n"
        "    def put(self, *a, **k): return _MockResp()\n"
        "    def delete(self, *a, **k): return _MockResp()\n"
        "    def request(self, *a, **k): return _MockResp()\n"
        "    def close(self): pass\n"
        "    def __enter__(self): return self\n"
        "    def __exit__(self, *a): pass\n"
        "_req.Session = _MockSession\n"
        "_req.exceptions = types.ModuleType('requests.exceptions')\n"
        "_req.exceptions.Timeout = TimeoutError\n"
        "_req.exceptions.ConnectionError = ConnectionError\n"
        "sys.modules['requests'] = _req\n"
        "sys.modules['requests.exceptions'] = _req.exceptions\n"
        "def _noop(*a, **k): return None\n"
        "builtins.breakpoint = _noop\n"
        "sys.breakpointhook = _noop\n"
        "_pdb_stub = types.ModuleType('pdb')\n"
        "_pdb_stub.set_trace = _noop\n"
        "_pdb_stub.pm = _noop\n"
        "sys.modules.setdefault('pdb', _pdb_stub)\n"
    )
